### ISSUE TITLE
Style général du site

### ISSUE THREAD

**Issue by arnopensource** [victormouracarvalho/BykeFrontend#5]
- [x] Enlever les pages inutiles du templates
- [x] Intégrer bootstrap
- [x] Créer une mise en page basique qui permettra d'avancer sur les features

**Comment by arnopensource** [comment]
Je travaille sur l'intégration bootstrap

**Comment by arnopensource** [comment]
#8

**Comment by arnopensource** [comment]
Voir #11

**Comment by victormouracarvalho** [comment]
Ok
